INSERT INTO `PacheteTV` VALUES (1, "Basic", "", "Generic", 1);
INSERT INTO `PacheteTV` VALUES (2, "Life Style", "", "Mixt", 2);
INSERT INTO `PacheteTV` VALUES (3, "Look", "", "Mixt", 2);
INSERT INTO `PacheteTV` VALUES (4, "Film+", "", "Filme", 4);
INSERT INTO `PacheteTV` VALUES (5, "AXN", "", "Filme", 4);
INSERT INTO `PacheteTV` VALUES (6, "FilmBox", "", "Filme", 4);
INSERT INTO `PacheteTV` VALUES (7, "HBO GO", "", "Filme", 4);
INSERT INTO `PacheteTV` VALUES (8, "Documentare+", "", "Documentare", 8);
INSERT INTO `PacheteTV` VALUES (9, "Nat Geo", "", "Documentare", 8);
INSERT INTO `PacheteTV` VALUES (10, "Discovery", "", "Documentare", 8);